### PR TITLE
Fix build with Qt 5.11 beta3 (drop qt5_use_modules)

### PR DESCRIPTION
**Pull request by a17r**
qt5_use_modules is gone in Qt 5.11_beta3 which breaks liblastfm.

### CODE REVIEW

**Comment by krop** [comment]
Cleanup include dirs looks wrong.
Qt5::Core Qt5::Network Qt5::Xml are link targets which 'make include_directories(...)' useless. You can't use it that way.

**Comment by krop** [comment]
+1 for the other commits.

**Comment by a17r** [comment]
> Cleanup include dirs looks wrong.
It appears we do not need it anyway, so I dropped it.

**Comment by ben-xo** [comment]
I have no real way to test this. Any changelog entries or perhaps a summary of what the changes in the PR do?

Does it still work with Qt4 as well?

**Comment by a17r** [comment]
> or perhaps a summary of what the changes in the PR do?

I like to think the git messages tell that story well. Slightly confused as I don't see a ChangeLog file in the project.

> Does it still work with Qt4 as well?

Yes it should still work fine with Qt4, but since Qt4 has been removed from our repositories I have no way to test this anymore.

**Comment by a17r** [comment]
@ben-xo incidentally, I found a system with Qt4 still installed, and was able to build this successfully with Qt4 enabled.

**Comment by a17r** [comment]
ping

**Comment by ben-xo** [comment]
Hi @a17r  - sorry there's been no action here. This library is essentially legacy / unmaintained at the moment.

I feel weird merging something that's not tested in-house to master, but I could merge it to a qt5 branch? Not sure what to suggest.

**Comment by krop** [comment]
@ben-xo tested in-house by who ? you're the only one that reacted to this pull request and distributions are using these changes for more than a year now.

**Comment by a17r** [comment]
> I feel weird merging something that's not tested in-house to master, but I could merge it to a qt5 branch? Not sure what to suggest.

The changes are rather straightforward and in cmake only, no need for a branch.

Removing all traces of Qt4 on the other hand could be done in a separate branch, or conversely, a qt4 branch with the current state to proceed with cleanup in master.

**Comment by ben-xo** [comment]
> Removing all traces of Qt4 on the other hand could be done in a separate branch, or conversely, a qt4 branch with the current state to proceed with cleanup in master.

This seems like a good option.

**Pull request merged**
